appName: "My-App"
appMode: dev
logLevel: debug
secret: "1234567890"
server:
  port: ${APP_PORT}
database:
  host: db
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  database: ${DB_DATABASE}
  port: ${DB_LOCAL_PORT}
