services:
  db:
    image: postgres:13.22
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/scripts/01.init.sql:/docker-entrypoint-initdb.d/01.init.sql
      - ./db/scripts/02.data.sql:/docker-entrypoint-initdb.d/02.data.sql
volumes:
  db:
